name: buem_env
channels:
  - conda-forge
  - default
dependencies:
  - python=3.13
  - coincbc
  - cvxpy
  - flask
  - gunicorn
  - joblib
  - jsonschema
  - matplotlib
  - numba
  - numpy
  - openpyxl
  - pandas
  - psutil
  - psycopg2
  - pulp
  - pvlib
  - pyarrow
  - python-dotenv
  - scipy
  - sympy
  - pip
  - pip:
    - marshmallow>=4.0.0
    - marshmallow-dataclass>=8.0.0